--------------------------------------------------------
--  파일이 생성됨 - 화요일-4월-07-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CART_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SPRING"."CART_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GUESTBOOK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SPRING"."GUESTBOOK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "SPRING"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REPLY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SPRING"."REPLY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD
--------------------------------------------------------

   CREATE SEQUENCE  "SPRING"."SEQ_BOARD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCT
--------------------------------------------------------

   CREATE SEQUENCE  "SPRING"."SEQ_PRODUCT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "SPRING"."ADMIN" 
   (	"USERID" VARCHAR2(50 BYTE), 
	"PASSWD" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"JOIN_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ATTACH
--------------------------------------------------------

  CREATE TABLE "SPRING"."ATTACH" 
   (	"FULLNAME" VARCHAR2(150 BYTE), 
	"BNO" NUMBER, 
	"REGDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "SPRING"."BOARD" 
   (	"BNO" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"WRITER" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"VIEWCNT" NUMBER DEFAULT 0, 
	"SHOW" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table BOOK
--------------------------------------------------------

  CREATE TABLE "SPRING"."BOOK" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(50 BYTE), 
	"AUTHOR" VARCHAR2(20 BYTE), 
	"PRICE" NUMBER DEFAULT 0, 
	"QTY" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "SPRING"."CART" 
   (	"CART_ID" NUMBER, 
	"USERID" VARCHAR2(50 BYTE), 
	"PRODUCT_ID" NUMBER, 
	"AMOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GUESTBOOK
--------------------------------------------------------

  CREATE TABLE "SPRING"."GUESTBOOK" 
   (	"IDX" NUMBER, 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PASWD" VARCHAR2(50 BYTE), 
	"CONTENT" VARCHAR2(200 BYTE), 
	"POST_DATE" DATE DEFAULT sysdate --작성일시

  
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "SPRING"."MEMBER" 
   (	"USERID" VARCHAR2(50 BYTE), 
	"PASSWD" VARCHAR2(50 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"JOIN_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMO
--------------------------------------------------------

  CREATE TABLE "SPRING"."MEMO" 
   (	"IDX" NUMBER, 
	"WRITER" VARCHAR2(50 BYTE), 
	"MEMO" VARCHAR2(500 BYTE), 
	"POST_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "SPRING"."PRODUCT" 
   (	"PRODUCT_ID" NUMBER, 
	"PRODUCT_NAME" VARCHAR2(50 BYTE), 
	"PRICE" NUMBER DEFAULT 0, 
	"DESCRIPTION" CLOB, 
	"PICTURE_URL" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table REPLY
--------------------------------------------------------

  CREATE TABLE "SPRING"."REPLY" 
   (	"RNO" NUMBER, 
	"BNO" NUMBER DEFAULT 0, 
	"REPLYTEXT" VARCHAR2(1000 BYTE), 
	"REPLYER" VARCHAR2(50 BYTE), 
	"REGDATE" DATE DEFAULT sysdate, 
	"UPDATEDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEST
--------------------------------------------------------

  CREATE TABLE "SPRING"."TEST" 
   (	"EMPNO" NUMBER(*,0), 
	"ENAME" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SPRING.ADMIN
SET DEFINE OFF;
Insert into SPRING.ADMIN (USERID,PASSWD,NAME,EMAIL,JOIN_DATE) values ('admin','1234','관리자',null,to_date('18/12/13','RR/MM/DD'));
REM INSERTING into SPRING.ATTACH
SET DEFINE OFF;
REM INSERTING into SPRING.BOARD
SET DEFINE OFF;
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (1,'제목','park',to_date('18/12/14','RR/MM/DD'),0,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (2,'aaa','kim',to_date('18/12/14','RR/MM/DD'),3,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (3,'b','kim',to_date('18/12/14','RR/MM/DD'),1,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (4,'c','kim',to_date('18/12/14','RR/MM/DD'),1,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (5,'d','kim',to_date('18/12/14','RR/MM/DD'),0,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (6,'e','kim',to_date('18/12/14','RR/MM/DD'),0,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (7,'f','kim',to_date('18/12/14','RR/MM/DD'),0,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (8,'d','kim',to_date('18/12/14','RR/MM/DD'),0,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (9,'q','kim',to_date('18/12/14','RR/MM/DD'),0,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (10,'s','kim',to_date('18/12/14','RR/MM/DD'),1,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (11,'k','kim',to_date('18/12/14','RR/MM/DD'),1,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (12,'q','kim',to_date('18/12/14','RR/MM/DD'),2,'Y');
Insert into SPRING.BOARD (BNO,TITLE,WRITER,REGDATE,VIEWCNT,SHOW) values (13,'w','kim',to_date('18/12/14','RR/MM/DD'),4,'Y');
REM INSERTING into SPRING.BOOK
SET DEFINE OFF;
Insert into SPRING.BOOK (ID,TITLE,AUTHOR,PRICE,QTY) values (1,'OS','Wiley',3070,50);
Insert into SPRING.BOOK (ID,TITLE,AUTHOR,PRICE,QTY) values (2,'OS','Wiley',3070,50);
REM INSERTING into SPRING.CART
SET DEFINE OFF;
Insert into SPRING.CART (CART_ID,USERID,PRODUCT_ID,AMOUNT) values (1,'qqq',1,10);
Insert into SPRING.CART (CART_ID,USERID,PRODUCT_ID,AMOUNT) values (2,'qqq',2,10);
Insert into SPRING.CART (CART_ID,USERID,PRODUCT_ID,AMOUNT) values (3,'qqq',3,10);
Insert into SPRING.CART (CART_ID,USERID,PRODUCT_ID,AMOUNT) values (4,'qqq',4,10);
Insert into SPRING.CART (CART_ID,USERID,PRODUCT_ID,AMOUNT) values (8,'kim',4,2);
Insert into SPRING.CART (CART_ID,USERID,PRODUCT_ID,AMOUNT) values (9,'kim',5,3);
Insert into SPRING.CART (CART_ID,USERID,PRODUCT_ID,AMOUNT) values (5,'kim',2,2);
Insert into SPRING.CART (CART_ID,USERID,PRODUCT_ID,AMOUNT) values (7,'kim',1,2);
REM INSERTING into SPRING.GUESTBOOK
SET DEFINE OFF;
REM INSERTING into SPRING.MEMBER
SET DEFINE OFF;
Insert into SPRING.MEMBER (USERID,PASSWD,NAME,EMAIL,JOIN_DATE) values ('kim','1234','김철수','kim@gmail.com',to_date('18/12/10','RR/MM/DD'));
REM INSERTING into SPRING.MEMO
SET DEFINE OFF;
Insert into SPRING.MEMO (IDX,WRITER,MEMO,POST_DATE) values (6,'a','a',to_date('18/12/13','RR/MM/DD'));
Insert into SPRING.MEMO (IDX,WRITER,MEMO,POST_DATE) values (7,'b','b',to_date('18/12/13','RR/MM/DD'));
Insert into SPRING.MEMO (IDX,WRITER,MEMO,POST_DATE) values (8,'c','c',to_date('18/12/13','RR/MM/DD'));
Insert into SPRING.MEMO (IDX,WRITER,MEMO,POST_DATE) values (9,'c','<p>c</p>',to_date('18/12/13','RR/MM/DD'));
Insert into SPRING.MEMO (IDX,WRITER,MEMO,POST_DATE) values (10,'d','<p><b>sadasdadas</b></p>',to_date('18/12/13','RR/MM/DD'));
Insert into SPRING.MEMO (IDX,WRITER,MEMO,POST_DATE) values (11,'k','<p>k</p>',to_date('18/12/13','RR/MM/DD'));
REM INSERTING into SPRING.PRODUCT
SET DEFINE OFF;
Insert into SPRING.PRODUCT (PRODUCT_ID,PRODUCT_NAME,PRICE,PICTURE_URL) values (5,'레몬',1500,'lemon.jpg');
REM INSERTING into SPRING.REPLY
SET DEFINE OFF;
Insert into SPRING.REPLY (RNO,BNO,REPLYTEXT,REPLYER,REGDATE,UPDATEDATE) values (1,1,'댓글...','kim',to_date('18/12/14','RR/MM/DD'),to_date('18/12/14','RR/MM/DD'));
Insert into SPRING.REPLY (RNO,BNO,REPLYTEXT,REPLYER,REGDATE,UPDATEDATE) values (2,2,'1111','kim',to_date('18/12/14','RR/MM/DD'),to_date('18/12/14','RR/MM/DD'));
REM INSERTING into SPRING.TEST
SET DEFINE OFF;
Insert into SPRING.TEST (EMPNO,ENAME) values (1,'사원1');
Insert into SPRING.TEST (EMPNO,ENAME) values (2,'사원2');
Insert into SPRING.TEST (EMPNO,ENAME) values (3,'사원3');
Insert into SPRING.TEST (EMPNO,ENAME) values (4,'사원4');
Insert into SPRING.TEST (EMPNO,ENAME) values (5,'사원5');
Insert into SPRING.TEST (EMPNO,ENAME) values (6,'사원6');
Insert into SPRING.TEST (EMPNO,ENAME) values (7,'사원7');
Insert into SPRING.TEST (EMPNO,ENAME) values (8,'사원8');
Insert into SPRING.TEST (EMPNO,ENAME) values (9,'사원9');
Insert into SPRING.TEST (EMPNO,ENAME) values (10,'사원10');
Insert into SPRING.TEST (EMPNO,ENAME) values (11,'사원11');
Insert into SPRING.TEST (EMPNO,ENAME) values (12,'사원12');
Insert into SPRING.TEST (EMPNO,ENAME) values (13,'사원13');
Insert into SPRING.TEST (EMPNO,ENAME) values (14,'사원14');
Insert into SPRING.TEST (EMPNO,ENAME) values (15,'사원15');
Insert into SPRING.TEST (EMPNO,ENAME) values (16,'사원16');
Insert into SPRING.TEST (EMPNO,ENAME) values (17,'사원17');
Insert into SPRING.TEST (EMPNO,ENAME) values (18,'사원18');
Insert into SPRING.TEST (EMPNO,ENAME) values (19,'사원19');
Insert into SPRING.TEST (EMPNO,ENAME) values (20,'사원20');
Insert into SPRING.TEST (EMPNO,ENAME) values (21,'사원21');
Insert into SPRING.TEST (EMPNO,ENAME) values (22,'사원22');
Insert into SPRING.TEST (EMPNO,ENAME) values (23,'사원23');
Insert into SPRING.TEST (EMPNO,ENAME) values (24,'사원24');
Insert into SPRING.TEST (EMPNO,ENAME) values (25,'사원25');
Insert into SPRING.TEST (EMPNO,ENAME) values (26,'사원26');
Insert into SPRING.TEST (EMPNO,ENAME) values (27,'사원27');
Insert into SPRING.TEST (EMPNO,ENAME) values (28,'사원28');
Insert into SPRING.TEST (EMPNO,ENAME) values (29,'사원29');
Insert into SPRING.TEST (EMPNO,ENAME) values (30,'사원30');
Insert into SPRING.TEST (EMPNO,ENAME) values (31,'사원31');
Insert into SPRING.TEST (EMPNO,ENAME) values (32,'사원32');
Insert into SPRING.TEST (EMPNO,ENAME) values (33,'사원33');
Insert into SPRING.TEST (EMPNO,ENAME) values (34,'사원34');
Insert into SPRING.TEST (EMPNO,ENAME) values (35,'사원35');
Insert into SPRING.TEST (EMPNO,ENAME) values (36,'사원36');
Insert into SPRING.TEST (EMPNO,ENAME) values (37,'사원37');
Insert into SPRING.TEST (EMPNO,ENAME) values (38,'사원38');
Insert into SPRING.TEST (EMPNO,ENAME) values (39,'사원39');
Insert into SPRING.TEST (EMPNO,ENAME) values (40,'사원40');
Insert into SPRING.TEST (EMPNO,ENAME) values (41,'사원41');
Insert into SPRING.TEST (EMPNO,ENAME) values (42,'사원42');
Insert into SPRING.TEST (EMPNO,ENAME) values (43,'사원43');
Insert into SPRING.TEST (EMPNO,ENAME) values (44,'사원44');
Insert into SPRING.TEST (EMPNO,ENAME) values (45,'사원45');
Insert into SPRING.TEST (EMPNO,ENAME) values (46,'사원46');
Insert into SPRING.TEST (EMPNO,ENAME) values (47,'사원47');
Insert into SPRING.TEST (EMPNO,ENAME) values (48,'사원48');
Insert into SPRING.TEST (EMPNO,ENAME) values (49,'사원49');
Insert into SPRING.TEST (EMPNO,ENAME) values (50,'사원50');
Insert into SPRING.TEST (EMPNO,ENAME) values (51,'사원51');
Insert into SPRING.TEST (EMPNO,ENAME) values (52,'사원52');
Insert into SPRING.TEST (EMPNO,ENAME) values (53,'사원53');
Insert into SPRING.TEST (EMPNO,ENAME) values (54,'사원54');
Insert into SPRING.TEST (EMPNO,ENAME) values (55,'사원55');
Insert into SPRING.TEST (EMPNO,ENAME) values (56,'사원56');
Insert into SPRING.TEST (EMPNO,ENAME) values (57,'사원57');
Insert into SPRING.TEST (EMPNO,ENAME) values (58,'사원58');
Insert into SPRING.TEST (EMPNO,ENAME) values (59,'사원59');
Insert into SPRING.TEST (EMPNO,ENAME) values (60,'사원60');
Insert into SPRING.TEST (EMPNO,ENAME) values (61,'사원61');
Insert into SPRING.TEST (EMPNO,ENAME) values (62,'사원62');
Insert into SPRING.TEST (EMPNO,ENAME) values (63,'사원63');
Insert into SPRING.TEST (EMPNO,ENAME) values (64,'사원64');
Insert into SPRING.TEST (EMPNO,ENAME) values (65,'사원65');
Insert into SPRING.TEST (EMPNO,ENAME) values (66,'사원66');
Insert into SPRING.TEST (EMPNO,ENAME) values (67,'사원67');
Insert into SPRING.TEST (EMPNO,ENAME) values (68,'사원68');
Insert into SPRING.TEST (EMPNO,ENAME) values (69,'사원69');
Insert into SPRING.TEST (EMPNO,ENAME) values (70,'사원70');
Insert into SPRING.TEST (EMPNO,ENAME) values (71,'사원71');
Insert into SPRING.TEST (EMPNO,ENAME) values (72,'사원72');
Insert into SPRING.TEST (EMPNO,ENAME) values (73,'사원73');
Insert into SPRING.TEST (EMPNO,ENAME) values (74,'사원74');
Insert into SPRING.TEST (EMPNO,ENAME) values (75,'사원75');
Insert into SPRING.TEST (EMPNO,ENAME) values (76,'사원76');
Insert into SPRING.TEST (EMPNO,ENAME) values (77,'사원77');
Insert into SPRING.TEST (EMPNO,ENAME) values (78,'사원78');
Insert into SPRING.TEST (EMPNO,ENAME) values (79,'사원79');
Insert into SPRING.TEST (EMPNO,ENAME) values (80,'사원80');
Insert into SPRING.TEST (EMPNO,ENAME) values (81,'사원81');
Insert into SPRING.TEST (EMPNO,ENAME) values (82,'사원82');
Insert into SPRING.TEST (EMPNO,ENAME) values (83,'사원83');
Insert into SPRING.TEST (EMPNO,ENAME) values (84,'사원84');
Insert into SPRING.TEST (EMPNO,ENAME) values (85,'사원85');
Insert into SPRING.TEST (EMPNO,ENAME) values (86,'사원86');
Insert into SPRING.TEST (EMPNO,ENAME) values (87,'사원87');
Insert into SPRING.TEST (EMPNO,ENAME) values (88,'사원88');
Insert into SPRING.TEST (EMPNO,ENAME) values (89,'사원89');
Insert into SPRING.TEST (EMPNO,ENAME) values (90,'사원90');
Insert into SPRING.TEST (EMPNO,ENAME) values (91,'사원91');
--------------------------------------------------------
--  Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "SPRING"."ATTACH" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."ATTACH" MODIFY ("BNO" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."ATTACH" ADD PRIMARY KEY ("FULLNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "SPRING"."MEMBER" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MEMBER" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MEMBER" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "SPRING"."PRODUCT" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "SPRING"."ADMIN" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."ADMIN" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."ADMIN" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."ADMIN" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMO
--------------------------------------------------------

  ALTER TABLE "SPRING"."MEMO" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MEMO" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MEMO" MODIFY ("MEMO" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."MEMO" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CART
--------------------------------------------------------

  ALTER TABLE "SPRING"."CART" MODIFY ("CART_ID" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CART" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CART" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CART" ADD PRIMARY KEY ("CART_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "SPRING"."BOARD" MODIFY ("BNO" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."BOARD" MODIFY ("WRITER" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."BOARD" ADD PRIMARY KEY ("BNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BOOK
--------------------------------------------------------

  ALTER TABLE "SPRING"."BOOK" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."BOOK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUESTBOOK
--------------------------------------------------------

  ALTER TABLE "SPRING"."GUESTBOOK" MODIFY ("IDX" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."GUESTBOOK" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."GUESTBOOK" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."GUESTBOOK" MODIFY ("PASWD" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."GUESTBOOK" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."GUESTBOOK" ADD PRIMARY KEY ("IDX")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "SPRING"."REPLY" MODIFY ("RNO" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."REPLY" MODIFY ("REPLYTEXT" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."REPLY" MODIFY ("REPLYER" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."REPLY" ADD PRIMARY KEY ("RNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ATTACH
--------------------------------------------------------

  ALTER TABLE "SPRING"."ATTACH" ADD CONSTRAINT "FK_BOARD_ATTACH" FOREIGN KEY ("BNO")
	  REFERENCES "SPRING"."BOARD" ("BNO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPLY
--------------------------------------------------------

  ALTER TABLE "SPRING"."REPLY" ADD CONSTRAINT "FK_BOARD" FOREIGN KEY ("BNO")
	  REFERENCES "SPRING"."BOARD" ("BNO") ENABLE;
